const STRIPE_LIVE_PUBLIC_KEY="<ADD_YOUR_KEY_HERE>" 
const STRIPE_LIVE_SECRET_KEY="<ADD_YOUR_KEY_HERE>" 
const STRIPE_TEST_PUBLIC_KEY="<ADD_YOUR_KEY_HERE>"
const STRIPE_TEST_SECRET_KEY="<ADD_YOUR_KEY_HERE>"

